export const TRIGGERS = {
    PRIZEPOOL_TOTAL     : 1000000,
    RAFFLE_POOL_LIMIT   : 0.8,
}

export const NOTIF_CODE = {
    PRIZEPOOL_TOTAL         : 'PRIZEPOOL_TOTAL',
    LUCKY_WHEEL_RESET       : 'LUCKY_WHEEL_RESET',
    ALMOST_FULL_RAFFLE      : 'ALMOST_FULL_RAFFLE',
    CAN_CLAIM_DAILY_LOGIN   : 'CAN_CLAIM_DAILY_LOGIN',
    DAILY_QUEST_RESET       : 'DAILY_QUEST_RESET',
    TICKET_AVAILABLE        : 'TICKET_AVAILABLE',
    PURCHASE_MOBILE_SUCCESS : 'PURCHASE_MOBILE_SUCCESS',
    PURCHASE_PLN_SUCCESS    : 'PURCHASE_PLN_SUCCESS',
    PURCHASE_PAM_SUCCESS    : 'PURCHASE_PAM_SUCCESS',
    PURCHASE_PAM_FAIL       : 'PURCHASE_PAM_FAIL',
    PURCHASE_PLN_FAIL       : 'PURCHASE_PLN_FAIL',
    PURCHASE_MOBILE_FAIL    : 'PURCHASE_MOBILE_FAIL',
    WITHDRAW_REVENUE_FAIL   : 'WITHDRAW_REVENUE_FAIL',
    WITHDRAW_COIN_FAIL      : 'WITHDRAW_COIN_FAIL',
    WITHDRAW_REVENUE_SUCCESS: 'WITHDRAW_REVENUE_SUCCESS',
    WITHDRAW_COIN_SUCCESS   : 'WITHDRAW_COIN_SUCCESS',
    STAMINA_RESET           : 'STAMINA_RESET',
    PURCHASE_SHOP_SUCCESS   : 'PURCHASE_SHOP_SUCCESS'
}