export const QUEUE_TYPE = {
    INSERT_RAFFLE_TICKET: 'INSERT_RAFFLE_TICKET',
    SEND_NOTIFICATION   : 'SEND_NOTIFICATION',
    SEND_MESSAGE        : 'SEND_MESSAGE',
    ASSIGN_USER_QUEST   : 'ASSIGN_USER_QUEST'
}